apiVersion: v1
kind: Service
metadata: 
  name: service-nodeport-bintalk
spec:
  ports:
    - name: web-port
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    svc: bintalk
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-bintalk
  labels:
    svc: bintalk
spec:
  containers:
  - name: bintalk-frontend
    image: kilo1089/bintalk-frontend
  - name: bintalk-backend
    image: kilo1089/bintalk-backend
  - name: bintalk-mariadb
    image: kilo1089/bintalk-mariadb
  # - name: bintalk-nginx
  #   image: kilo1089/bintalk-nginx
  #   ports:
  #   - containerPort: 80
  #     protocol: TCP
