apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bintalk
spec:
  replicas: 2
  selector:
    matchLabels:
      svc: bintalk
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        svc: bintalk
    spec:
      containers:
      - name: bintalk-frontend
        image: kilo1089/bintalk-frontend
        ports:
        - containerPort: 80
      - name: bintalk-backend
        image: kilo1089/bintalk-backend
      # - name: bintalk-mariadb
      #   image: kilo1089/bintalk-mariadb
---
apiVersion: v1
kind: Service
metadata: 
  name: service-nodeport-bintalk
spec:
  ports:
    - name: web-port
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    svc: bintalk
  type: NodePort